### ISSUE TITLE
local LLM´s -- nice to have

### ISSUE THREAD

**Issue by weekendkoder** [akudo7/kudos-gpt#1]
Hello.

It would be nice, to setup local LLMs via an API. 

I played around with "Jan AI". It is super easy and has lot of features, like running a "Local API Server". This can be used with
Continue for example.  And you are connected with VScode. Maybe you can get some inspiration from other solutions, like:
"Firecoder Chat" for VScode. An very nice "install & instant start" solution.

**Comment by akudo7** [comment]
@weekendkoder 

Hi, thanks for contacting me.
Our kudos-gpt has focused on accessing LLMs via the Flowise for the assistant feature. Isn't that comfortable for you?
If you wanna use the "Jan AI" on the copilot feature, I will try to find a way to support it. But as I read the github of it, most of the models work on it are loadable on the Flowise.
Anyway, let us keep in touch!
Akira

**Comment by weekendkoder** [comment]
Hi.

Oh ok. Maybe i need to investigate about "Flowise". I guess i did not get the workflow how to use kudos-gpt the right way. Thanks for the hint. Usually i use offline local AI´s. Mostly with "Jan Ai" and "LM Studio Ai". I will try it out, on my next opportunity

**Comment by akudo7** [comment]
@weekendkoder

Hi, thanks for your reply.
I recommend you watch the link below if you are interested in Flowise.
https://www.youtube.com/watch?v=tD6fwQyUIJE&list=PL4HikwTaYE0HDOuXMm5sU6DH6_ZrHBLSJ
I know you love it!
