### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by jjamgmv** [akudo7/kudos-gpt#2]
I receive the error Command Kudos-gpt.AssistantOnOff not found

**Comment by akudo7** [comment]
In theory, this message means that validating the token has failed.
Could you let me know if you've set the token? 
See in detail at the "Settings / ver 4.2.0 / 01. Set the token: New feature is available" again. 
Thanks

**Comment by akudo7** [comment]
I'll close this ticket because of the inactive. Feel free to open it again, if you need more help.

**Comment by akudo7** [comment]
I'll close this ticket because of the inactive. Feel free to open it again, if you need more help.
